import ezdxf as dxf
from point import *

def main(width, heigh, quantity, EI150 = False, path = str()):
    doc = dxf.new()
    doc.layers.add("FIGURE", color=2) 
    msp = doc.modelspace()
    p = point()
    p.msp = msp

    p.go_line(72, 0)
    p.go_arc(8, 3)
    p.go_arc(7, 3)
    p.go_line(0, -19)
    p.go_arc(6, 3)
    p.go_arc(5, 3)
    p.go_line(-47, 0)
    p.set_xy(20, -30)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.set_xy(20, -30)
    p.go_line(0, -47)
    p.go_arc(6, 3)
    p.go_arc(5, 3)
    p.go_line(-19, 0)
    p.go_arc(4, 3)
    p.go_arc(3, 3)
    p.go_line(0, 72)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_init()

    p.set_xy(7.878, -6.515)
    p.go_angle(-45, 10)
    p.go_arc(7, 4.5)
    p.go_arc(6, 4.5)
    p.go_arc(5, 4.5)
    p.go_arc(4, 4.5)
    p.go_angle(135, 10)
    p.go_arc(3, 4.5)
    p.go_arc(2, 4.5)
    p.go_arc(1, 4.5)
    p.go_arc(8, 4.5)

    doc.saveas(path+"уголок "+str(width)+'x'+str(heigh)+' 0,8мм '+ str(quantity * 8 + int(EI150) * 8)+'шт.dxf')