import ezdxf as dxf
from point import *

def main(width, heigh, quantity = 1, path = str()):
    doc = dxf.new()
    doc.layers.add("FIGURE", color=2) 
    msp = doc.modelspace()
    p = point()
    p.msp = msp

    p.go_line(62.4, 0)
    p.go_arc(8, 5)
    p.go_arc(7, 5)
    p.go_line(0, -26.44)
    p.go_line(37.08, 0)
    p.go_arc(8, 5)
    p.go_arc(7, 5)
    p.go_line(0, -(285.6 + (heigh - 300)))
    p.go_arc(6, 5)
    p.go_arc(5, 5)
    p.go_line(-37.08, 0)
    p.go_line(0, -26.44)
    p.go_arc(6, 5)
    p.go_arc(5, 5)
    p.go_line(-62.4, 0)
    p.go_arc(4, 5)
    p.go_arc(3, 5)
    p.go_line(0, 26.44)
    p.go_line(-37.08, 0)
    p.go_arc(4, 5)
    p.go_arc(3, 5)
    p.go_line(0, 285.6 + (heigh - 300))
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_line(37.08, 0)
    p.go_line(0, 26.44)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_init()
    p.circle(-21.36, -96.44, 4.9/2)
    p.circle(0, -(165.6 + (heigh - 300)), 4.9/2)

    doc.saveas(path+"профиль 1_2 "+str(width)+'x'+str(heigh)+' 0,8мм '+ str(quantity*2)+'шт.dxf')
