import ezdxf as dxf
from point import *


def profile(width, heigh, quantity, path=str(), ver=False):
    doc = dxf.new()
    doc.layers.add("FIGURE", color=2)
    msp = doc.modelspace()
    p = point()
    p.msp = msp

    p.go_line(221.28, 0)
    p.set_xy(218.78, 2.5)
    p.go_arc(8, 2.5)
    p.go_arc(7, 2.5)
    p.set_xy(218.78, 2.5)
    p.go_line(-47.1, 0)
    p.go_arc(4, 5)
    p.go_arc(3, 5)
    p.go_line(0, 16)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_line(78.44, 0)
    p.go_arc(8, 5)
    p.go_arc(7, 5)
    p.go_line(0, -(width + 46))
    p.go_arc(6, 5)
    p.go_arc(5, 5)
    p.go_line(-78.44, 0)
    p.go_arc(4, 5)
    p.go_arc(3, 5)
    p.go_line(0, 16)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_line(47.1, 0)
    p.set_xy(221.28, - width + 1)
    p.go_arc(6, 2.5)
    p.go_arc(5, 2.5)
    p.set_xy(221.28, - width + 1)
    p.go_line(-221.28, 0)
    p.set_xy(2.5, - 1.51 - width)
    p.go_arc(4, 2.5)
    p.go_arc(3, 2.5)
    p.set_xy(2.5, - 1.51 - width)
    p.go_line(47.1, 0)
    p.go_arc(8, 5)
    p.go_arc(7, 5)
    p.go_line(0, -16)
    p.go_arc(6, 5)
    p.go_arc(5, 5)
    p.go_line(-78.44, 0)
    p.go_arc(4, 5)
    p.go_arc(3, 5)
    p.go_line(0, width + 46)
    p.go_arc(2, 5)
    p.go_arc(1, 5)
    p.go_line(78.44, 0)
    p.go_arc(8, 5)
    p.go_arc(7, 5)
    p.go_line(0, -16)
    p.go_arc(6, 5)
    p.go_arc(5, 5)
    p.go_line(-47.1, 0)
    p.set_xy(0, 0)
    p.go_arc(2, 2.5)
    p.go_arc(1, 2.5)

    # отверстия в уголках

    p.set_xy(17.6, 15.5)
    p.circle(0, 0, 4.9/2)
    p.circle(0, -30 - width, 4.9/2)
    p.circle(27, 0, 4.9/2)
    p.circle(0, 30 + width, 4.9/2)

    p.set_xy(176.68, 15.5)
    p.circle(0, 0, 4.9/2)
    p.circle(0, -30 - width, 4.9/2)
    p.circle(27, 0, 4.9/2)
    p.circle(0, 30 + width, 4.9/2)

    # проушины под крепление к воздуховоду и решёткам

    # верхний левый угол
    p.set_xy(-10.84, 8.78)
    p.go_angle(135, 10)
    p.go_arc(3, 4.5)
    p.go_arc(2, 4.5)
    p.go_arc(1, 4.5)
    p.go_arc(8, 4.5)
    p.go_angle(-45, 10)
    p.go_arc(7, 4.5)
    p.go_arc(6, 4.5)
    p.go_arc(5, 4.5)
    p.go_arc(4, 4.5)

    # верхний правый угол
    p.set_xy(225.76, 15.15)
    p.go_angle(45, 10)
    p.go_arc(1, 4.5)
    p.go_arc(8, 4.5)
    p.go_arc(7, 4.5)
    p.go_arc(6, 4.5)
    p.go_angle(-135, 10)
    p.go_arc(5, 4.5)
    p.go_arc(4, 4.5)
    p.go_arc(3, 4.5)
    p.go_arc(2, 4.5)

    # нижний левый угол
    p.set_xy(-17.92, -14.85 - width)
    p.go_angle(45, 10)
    p.go_arc(1, 4.5)
    p.go_arc(8, 4.5)
    p.go_arc(7, 4.5)
    p.go_arc(6, 4.5)
    p.go_angle(-135, 10)
    p.go_arc(5, 4.5)
    p.go_arc(4, 4.5)
    p.go_arc(3, 4.5)
    p.go_arc(2, 4.5)

    # нижний правый угол
    p.set_xy(232.83, -21.3 - width)
    p.go_angle(135, 10)
    p.go_arc(3, 4.5)
    p.go_arc(2, 4.5)
    p.go_arc(1, 4.5)
    p.go_arc(8, 4.5)
    p.go_angle(-45, 10)
    p.go_arc(7, 4.5)
    p.go_arc(6, 4.5)
    p.go_arc(5, 4.5)
    p.go_arc(4, 4.5)

    # крепление к профилю 1
    p.set_xy(39.44, -14)
    p.circle(0, 0, 4.9/2)
    p.circle(71.2, 0, 4.9/2)
    p.circle(71.2, 0, 4.9/2)
    p.circle(0, - width + 29, 4.9/2)
    p.circle(-71.2, 0, 4.9/2)
    p.circle(-71.2, 0, 4.9/2)

    # крепление уголков
    if width > 100:
        p.set_xy(79.94, -48.5)
        p.circle(0, 0, 4.9/2)
        p.circle(0, - width/2 + 49, 4.9/2)
        p.circle(0, - width/2 + 49, 4.9/2)
    else:
        p.set_xy(113.78, -38.5)
        p.circle(0, 0, 2.45)
        p.circle(0, -22, 2.45)

    # метка
    if ver:
        p.set_xy(-30.94, -3 - width/2)
        p.go_arc(4, 1.5)
        p.go_arc(3, 1.5)
        p.go_arc(2, 1.5)
        p.go_arc(1, 1.5)
        p.go_arc(4, 2.02)
        p.go_arc(3, 2.02)
        p.go_arc(2, 2.02)
        p.go_arc(1, 2.02)
        p.go_line(1.5, 0)
        p.go_line(0, -7)
        p.go_line(-0.75, 0)
        p.go_line(0, 6.21)
        p.go_line(-0.75, 0)
        p.set_xy(-30.94, -3 - width/2)
        p.go_line(0, 0.75)
        p.go_arc(4, 1.5/2)
        p.go_arc(3, 1.5/2)
        p.go_arc(2, 1.5/2)
        p.go_arc(1, 1.5/2)
        p.go_line(0, 1.46)
        p.go_arc(4, 2.54/2)
        p.go_arc(3, 2.54/2)
        p.go_arc(2, 2.54/2)
        p.go_arc(1, 2.54/2)
        doc.saveas(path+"Профиль 2 верх "+str(width)+'x' +
                   str(heigh)+' 0,8мм ' + str(quantity)+'шт.dxf')
    else:
        p.set_xy(249.92, - width/2 + 4)
        p.go_line(0, -7)
        p.go_line(0.75, 0)
        p.go_line(0, 3.125)
        p.go_line(2.5, 0)
        p.go_line(0, -3.125)
        p.go_line(0.75, 0)
        p.go_line(0, 7)
        p.go_line(-0.75, 0)
        p.go_line(0, -3.125)
        p.go_line(-2.5, 0)
        p.go_line(0, 3.125)
        p.go_line(-0.75, 0)

        doc.saveas(path+"Профиль 2 низ "+str(width)+'x' +
                   str(heigh)+' 0,8мм ' + str(quantity)+'шт.dxf')


def main(width, heigh, quantity, path=str()):
    profile(width, heigh, quantity, path, False)
    profile(width, heigh, quantity, path, True)
